import {faCirclePlus,faImage,faTimesCircle,faCaretDown,} from '@fortawesome/free-solid-svg-icons';
import {faArrowLeft,faUser,faPaw,faCalendar,faWeight,faPalette,faVenusMars,} from '@fortawesome/free-solid-svg-icons';
import { faLock, faEnvelope, faAddressCard, faCheckCircle, } from '@fortawesome/free-solid-svg-icons';
import { faMessage } from '@fortawesome/free-solid-svg-icons';
import { faRightFromBracket } from '@fortawesome/free-solid-svg-icons';
import {CheckCircleIcon as CheckIcon, XCircleIcon as XIcon, ChatBubbleLeftRightIcon as ForumSolid, ChatBubbleBottomCenterTextIcon as Bubble,} from 'react-native-heroicons/solid';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import { faGear, faPhone, faClock, faCircleArrowDown  } from '@fortawesome/free-solid-svg-icons';
import {faCommentDots,faCircleXmark,} from '@fortawesome/free-solid-svg-icons';
import { TrashIcon as Trash } from 'react-native-heroicons/solid';
import { ArrowLeftIcon as BackIcon } from 'react-native-heroicons/solid';
import { faLocationDot } from '@fortawesome/free-solid-svg-icons';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import {Cog6ToothIcon as CogIcon,UserIcon as User,BuildingOfficeIcon as ClinicIcon, ArrowRightOnRectangleIcon as ExitIcon, } from 'react-native-heroicons/solid';
