
// compilation of icons used 

import {
    faCirclePlus,
    faImage,
    faTimesCircle,
    faCaretDown,
    faArrowLeft,
    faUser,
    faPaw,
    faCalendar,
    faWeight,
    faPalette,
    faVenusMars,
    faLock,
    faEnvelope,
    faAddressCard,
    faCheckCircle,
    faMessage,
    faRightFromBracket,
    faGear,
    faCog,
    faPhone,
    faClock,
    faCircleArrowDown,
    faCommentDots,
    faComment,
    faCircleXmark,
    faLocationDot,
    faArrowRight,
    faMagnifyingGlass,
} from '@fortawesome/free-solid-svg-icons';

import {
    CheckCircleIcon as CheckIcon,
    XCircleIcon as XIcon,
    ChatBubbleLeftRightIcon as ForumSolid,
    ChatBubbleBottomCenterTextIcon as Bubble,
    ArrowLeftIcon as BackIcon,
    TrashIcon as Trash,
    Cog6ToothIcon as CogIcon,
    UserIcon as User,
    BuildingOfficeIcon as ClinicIcon,
    ArrowRightOnRectangleIcon as ExitIcon,
    HomeIcon as HomeSolid,
    ChatBubbleOvalLeftEllipsisIcon as ChatBubbleLeftSolid,
    PlusCircleIcon as PlusCircleSolid,
    UserIcon as UserSolid,
    MagnifyingGlassIcon as MagnifyingGlass,
    ChatBubbleLeftIcon as ChatBubbleLeftIcon,
} from 'react-native-heroicons/solid';

import MaterialIcons from 'react-native-vector-icons/MaterialIcons';

export {
    faCirclePlus,
    faImage,
    faTimesCircle,
    faCaretDown,
    faArrowLeft,
    faUser,
    faPaw,
    faComment,
    faCalendar,
    faWeight,
    faPalette,
    faVenusMars,
    faLock,
    faEnvelope,
    faAddressCard,
    faCheckCircle,
    faMessage,
    faRightFromBracket,
    CheckIcon,
    XIcon,
    ForumSolid,
    Bubble,
    MaterialIcons,
    faCog,
    faGear,
    faPhone,
    faClock,
    faCircleArrowDown,
    faCommentDots,
    faCircleXmark,
    Trash,
    BackIcon,
    faLocationDot,
    faArrowRight,
    CogIcon,
    User,
    ClinicIcon,
    ExitIcon,
    HomeSolid,
    MagnifyingGlass,
    ChatBubbleLeftSolid,
    ChatBubbleLeftIcon,
    PlusCircleSolid,
    UserSolid,
    faMagnifyingGlass,

};
